import { ECMC_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import {
    SUPERADMIN,
    ADMIN,
    STUDENT,
} from '@/constants/roles.constant'

const ecmcNavigationConfig = [
    // ─── ADMIN ────────────────────────────────────────────────────
    {
        key: 'ecmc.admin',
        path: '',
        title: 'School Admin',
        translateKey: 'nav.ecmc.admin',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, SUPERADMIN],
        subMenu: [
            {
                key: 'ecmc.admin.dashboard',
                path: `${ECMC_PREFIX_PATH}/admin/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.admin.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.quiz',
                path: '',
                title: 'Quiz & Exams',
                translateKey: 'nav.ecmc.quiz',
                icon: 'clipboardCheck',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.quiz.list',
                        path: `${ECMC_PREFIX_PATH}/quiz`,
                        title: 'All Quizzes',
                        translateKey: 'nav.ecmc.quiz.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.quiz.categories',
                        path: `${ECMC_PREFIX_PATH}/quiz/categories`,
                        title: 'Categories',
                        translateKey: 'nav.ecmc.quiz.categories',
                        icon: 'folder',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.practice',
                path: '',
                title: 'Practice Sets',
                translateKey: 'nav.ecmc.practice',
                icon: 'pencil',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.practice.list',
                        path: `${ECMC_PREFIX_PATH}/practice`,
                        title: 'All Practice Sets',
                        translateKey: 'nav.ecmc.practice.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.qbank',
                path: '',
                title: 'Question Bank',
                translateKey: 'nav.ecmc.qbank',
                icon: 'bookOpen',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.qbank.stats',
                        path: `${ECMC_PREFIX_PATH}/qbank/stats`,
                        title: 'Dashboard',
                        translateKey: 'nav.ecmc.qbank.stats',
                        icon: 'chartBar',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.questions',
                        path: `${ECMC_PREFIX_PATH}/qbank/questions`,
                        title: 'Questions',
                        translateKey: 'nav.ecmc.qbank.questions',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.subjects',
                        path: `${ECMC_PREFIX_PATH}/qbank/subjects`,
                        title: 'Subjects',
                        translateKey: 'nav.ecmc.qbank.subjects',
                        icon: 'folder',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.topics',
                        path: `${ECMC_PREFIX_PATH}/qbank/topics`,
                        title: 'Topics',
                        translateKey: 'nav.ecmc.qbank.topics',
                        icon: 'list',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.tags',
                        path: `${ECMC_PREFIX_PATH}/qbank/tags`,
                        title: 'Tags',
                        translateKey: 'nav.ecmc.qbank.tags',
                        icon: 'tag',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.import',
                        path: `${ECMC_PREFIX_PATH}/qbank/import`,
                        title: 'Import',
                        translateKey: 'nav.ecmc.qbank.import',
                        icon: 'upload',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.blog',
                path: '',
                title: 'Blog',
                translateKey: 'nav.ecmc.blog',
                icon: 'edit',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.blog.list',
                        path: `${ECMC_PREFIX_PATH}/blog`,
                        title: 'All Posts',
                        translateKey: 'nav.ecmc.blog.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.blog.categories',
                        path: `${ECMC_PREFIX_PATH}/blog-categories`,
                        title: 'Categories',
                        translateKey: 'nav.ecmc.blog.categories',
                        icon: 'folder',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.blog.tags',
                        path: `${ECMC_PREFIX_PATH}/blog-tags`,
                        title: 'Tags',
                        translateKey: 'nav.ecmc.blog.tags',
                        icon: 'tag',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.blog.comments',
                        path: `${ECMC_PREFIX_PATH}/blog-comments`,
                        title: 'Comments',
                        translateKey: 'nav.ecmc.blog.comments',
                        icon: 'chat',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
        ],
    },

    // ─── STUDENT ──────────────────────────────────────────────────
    {
        key: 'ecmc.student',
        path: '',
        title: 'Student Portal',
        translateKey: 'nav.ecmc.student',
        icon: 'graduationCap',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [STUDENT],
        subMenu: [
            {
                key: 'ecmc.student.mypracticesets',
                path: `${ECMC_PREFIX_PATH}/student/my-practice-sets`,
                title: 'Practice Sets',
                translateKey: 'nav.ecmc.student.mypracticesets',
                icon: 'pencil',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.myquizzes',
                path: `${ECMC_PREFIX_PATH}/student/my-quizzes`,
                title: 'My Quizzes',
                translateKey: 'nav.ecmc.student.myquizzes',
                icon: 'clipboardCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.myattempts',
                path: `${ECMC_PREFIX_PATH}/student/my-attempts`,
                title: 'My Attempts',
                translateKey: 'nav.ecmc.student.myattempts',
                icon: 'chartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
        ],
    },
]

export default ecmcNavigationConfig
