import { ECMC_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import {
    SUPERADMIN,
    ADMIN,
    TEACHER,
    STUDENT,
    PARENT,
} from '@/constants/roles.constant'

const ecmcNavigationConfig = [
    // ─── SUPERADMIN ───────────────────────────────────────────────
    {
        key: 'ecmc.superadmin',
        path: '',
        title: 'Administration',
        translateKey: 'nav.ecmc.superadmin',
        icon: 'shield',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [SUPERADMIN],
        subMenu: [
            {
                key: 'ecmc.superadmin.dashboard',
                path: `${ECMC_PREFIX_PATH}/superadmin/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.superadmin.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.superadmin.users',
                path: `${ECMC_PREFIX_PATH}/superadmin/users`,
                title: 'User Management',
                translateKey: 'nav.ecmc.superadmin.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.superadmin.schools',
                path: `${ECMC_PREFIX_PATH}/superadmin/schools`,
                title: 'School Management',
                translateKey: 'nav.ecmc.superadmin.schools',
                icon: 'building',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.superadmin.reports',
                path: `${ECMC_PREFIX_PATH}/superadmin/reports`,
                title: 'Reports',
                translateKey: 'nav.ecmc.superadmin.reports',
                icon: 'chartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.superadmin.settings',
                path: `${ECMC_PREFIX_PATH}/superadmin/settings`,
                title: 'System Settings',
                translateKey: 'nav.ecmc.superadmin.settings',
                icon: 'settings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
        ],
    },

    // ─── ADMIN ────────────────────────────────────────────────────
    {
        key: 'ecmc.admin',
        path: '',
        title: 'School Admin',
        translateKey: 'nav.ecmc.admin',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, SUPERADMIN],
        subMenu: [
            {
                key: 'ecmc.admin.dashboard',
                path: `${ECMC_PREFIX_PATH}/admin/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.admin.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.admin.teachers',
                path: `${ECMC_PREFIX_PATH}/admin/teachers`,
                title: 'Teachers',
                translateKey: 'nav.ecmc.admin.teachers',
                icon: 'userCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.admin.students',
                path: `${ECMC_PREFIX_PATH}/admin/students`,
                title: 'Students',
                translateKey: 'nav.ecmc.admin.students',
                icon: 'graduationCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.admin.parents',
                path: `${ECMC_PREFIX_PATH}/admin/parents`,
                title: 'Parents',
                translateKey: 'nav.ecmc.admin.parents',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.admin.classes',
                path: `${ECMC_PREFIX_PATH}/admin/classes`,
                title: 'Classes',
                translateKey: 'nav.ecmc.admin.classes',
                icon: 'bookOpen',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.admin.reports',
                path: `${ECMC_PREFIX_PATH}/admin/reports`,
                title: 'Reports',
                translateKey: 'nav.ecmc.admin.reports',
                icon: 'chartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
        ],
    },

    // ─── TEACHER ──────────────────────────────────────────────────
    {
        key: 'ecmc.teacher',
        path: '',
        title: 'Teacher Portal',
        translateKey: 'nav.ecmc.teacher',
        icon: 'chalkboard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [TEACHER],
        subMenu: [
            {
                key: 'ecmc.teacher.dashboard',
                path: `${ECMC_PREFIX_PATH}/teacher/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.teacher.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
            {
                key: 'ecmc.teacher.classes',
                path: `${ECMC_PREFIX_PATH}/teacher/classes`,
                title: 'My Classes',
                translateKey: 'nav.ecmc.teacher.classes',
                icon: 'bookOpen',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
            {
                key: 'ecmc.teacher.assignments',
                path: `${ECMC_PREFIX_PATH}/teacher/assignments`,
                title: 'Assignments',
                translateKey: 'nav.ecmc.teacher.assignments',
                icon: 'clipboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
            {
                key: 'ecmc.teacher.performance',
                path: `${ECMC_PREFIX_PATH}/teacher/performance`,
                title: 'Student Performance',
                translateKey: 'nav.ecmc.teacher.performance',
                icon: 'trendingUp',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
            {
                key: 'ecmc.teacher.attendance',
                path: `${ECMC_PREFIX_PATH}/teacher/attendance`,
                title: 'Attendance',
                translateKey: 'nav.ecmc.teacher.attendance',
                icon: 'calendarCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
        ],
    },

    // ─── STUDENT ──────────────────────────────────────────────────
    {
        key: 'ecmc.student',
        path: '',
        title: 'Student Portal',
        translateKey: 'nav.ecmc.student',
        icon: 'graduationCap',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [STUDENT],
        subMenu: [
            {
                key: 'ecmc.student.dashboard',
                path: `${ECMC_PREFIX_PATH}/student/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.student.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.courses',
                path: `${ECMC_PREFIX_PATH}/student/courses`,
                title: 'My Courses',
                translateKey: 'nav.ecmc.student.courses',
                icon: 'bookOpen',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.assignments',
                path: `${ECMC_PREFIX_PATH}/student/assignments`,
                title: 'Assignments',
                translateKey: 'nav.ecmc.student.assignments',
                icon: 'clipboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.grades',
                path: `${ECMC_PREFIX_PATH}/student/grades`,
                title: 'Grades',
                translateKey: 'nav.ecmc.student.grades',
                icon: 'award',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.schedule',
                path: `${ECMC_PREFIX_PATH}/student/schedule`,
                title: 'Schedule',
                translateKey: 'nav.ecmc.student.schedule',
                icon: 'calendar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
        ],
    },

    // ─── PARENT ───────────────────────────────────────────────────
    {
        key: 'ecmc.parent',
        path: '',
        title: 'Parent Portal',
        translateKey: 'nav.ecmc.parent',
        icon: 'home',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [PARENT],
        subMenu: [
            {
                key: 'ecmc.parent.dashboard',
                path: `${ECMC_PREFIX_PATH}/parent/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.parent.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
            {
                key: 'ecmc.parent.children',
                path: `${ECMC_PREFIX_PATH}/parent/children`,
                title: 'My Children',
                translateKey: 'nav.ecmc.parent.children',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
            {
                key: 'ecmc.parent.attendance',
                path: `${ECMC_PREFIX_PATH}/parent/attendance`,
                title: 'Attendance',
                translateKey: 'nav.ecmc.parent.attendance',
                icon: 'calendarCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
            {
                key: 'ecmc.parent.grades',
                path: `${ECMC_PREFIX_PATH}/parent/grades`,
                title: 'Grades',
                translateKey: 'nav.ecmc.parent.grades',
                icon: 'award',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
            {
                key: 'ecmc.parent.messages',
                path: `${ECMC_PREFIX_PATH}/parent/messages`,
                title: 'Messages',
                translateKey: 'nav.ecmc.parent.messages',
                icon: 'mail',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
        ],
    },
]

export default ecmcNavigationConfig
