import { ECMC_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import {
    SUPERADMIN,
    ADMIN,
    STUDENT,
    TEACHER,
    PARENT,
} from '@/constants/roles.constant'

const ecmcNavigationConfig = [
    // ─── ADMIN ────────────────────────────────────────────────────
    {
        key: 'ecmc.admin',
        path: '',
        title: 'School Admin',
        translateKey: 'nav.ecmc.admin',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, SUPERADMIN],
        subMenu: [
            {
                key: 'ecmc.admin.dashboard',
                path: `${ECMC_PREFIX_PATH}/admin/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.admin.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.quiz',
                path: '',
                title: 'Quiz & Exams',
                translateKey: 'nav.ecmc.quiz',
                icon: 'clipboardCheck',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.quiz.list',
                        path: `${ECMC_PREFIX_PATH}/quiz`,
                        title: 'All Quizzes',
                        translateKey: 'nav.ecmc.quiz.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.quiz.categories',
                        path: `${ECMC_PREFIX_PATH}/quiz/categories`,
                        title: 'Categories',
                        translateKey: 'nav.ecmc.quiz.categories',
                        icon: 'folder',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.practice',
                path: '',
                title: 'Practice Sets',
                translateKey: 'nav.ecmc.practice',
                icon: 'pencil',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.practice.list',
                        path: `${ECMC_PREFIX_PATH}/practice`,
                        title: 'All Practice Sets',
                        translateKey: 'nav.ecmc.practice.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.qbank',
                path: '',
                title: 'Question Bank',
                translateKey: 'nav.ecmc.qbank',
                icon: 'bookOpen',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.qbank.stats',
                        path: `${ECMC_PREFIX_PATH}/qbank/stats`,
                        title: 'Dashboard',
                        translateKey: 'nav.ecmc.qbank.stats',
                        icon: 'chartBar',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.questions',
                        path: `${ECMC_PREFIX_PATH}/qbank/questions`,
                        title: 'Questions',
                        translateKey: 'nav.ecmc.qbank.questions',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.subjects',
                        path: `${ECMC_PREFIX_PATH}/qbank/subjects`,
                        title: 'Subjects',
                        translateKey: 'nav.ecmc.qbank.subjects',
                        icon: 'folder',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.topics',
                        path: `${ECMC_PREFIX_PATH}/qbank/topics`,
                        title: 'Topics',
                        translateKey: 'nav.ecmc.qbank.topics',
                        icon: 'list',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.tags',
                        path: `${ECMC_PREFIX_PATH}/qbank/tags`,
                        title: 'Tags',
                        translateKey: 'nav.ecmc.qbank.tags',
                        icon: 'tag',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.qbank.import',
                        path: `${ECMC_PREFIX_PATH}/qbank/import`,
                        title: 'Import',
                        translateKey: 'nav.ecmc.qbank.import',
                        icon: 'upload',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.plans',
                path: '',
                title: 'Plans & Subscriptions',
                translateKey: 'nav.ecmc.plans',
                icon: 'creditCard',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.plans.list',
                        path: `${ECMC_PREFIX_PATH}/plans`,
                        title: 'Plans',
                        translateKey: 'nav.ecmc.plans.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.plans.subscriptions',
                        path: `${ECMC_PREFIX_PATH}/subscriptions`,
                        title: 'Subscriptions',
                        translateKey: 'nav.ecmc.plans.subscriptions',
                        icon: 'users',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ecmc.blog',
                path: '',
                title: 'Blog',
                translateKey: 'nav.ecmc.blog',
                icon: 'edit',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPERADMIN],
                subMenu: [
                    {
                        key: 'ecmc.blog.list',
                        path: `${ECMC_PREFIX_PATH}/blog`,
                        title: 'All Posts',
                        translateKey: 'nav.ecmc.blog.list',
                        icon: 'docList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.blog.categories',
                        path: `${ECMC_PREFIX_PATH}/blog-categories`,
                        title: 'Categories',
                        translateKey: 'nav.ecmc.blog.categories',
                        icon: 'folder',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.blog.tags',
                        path: `${ECMC_PREFIX_PATH}/blog-tags`,
                        title: 'Tags',
                        translateKey: 'nav.ecmc.blog.tags',
                        icon: 'tag',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'ecmc.blog.comments',
                        path: `${ECMC_PREFIX_PATH}/blog-comments`,
                        title: 'Comments',
                        translateKey: 'nav.ecmc.blog.comments',
                        icon: 'chat',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, SUPERADMIN],
                        subMenu: [],
                    },
                ],
            },
        ],
    },

    // ─── SUPERADMIN ───────────────────────────────────────────────
    {
        key: 'ecmc.superadmin',
        path: '',
        title: 'Super Admin',
        translateKey: 'nav.ecmc.superadmin',
        icon: 'shield',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [SUPERADMIN],
        subMenu: [
            {
                key: 'ecmc.superadmin.dashboard',
                path: `${ECMC_PREFIX_PATH}/superadmin/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.superadmin.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.superadmin.users',
                path: `${ECMC_PREFIX_PATH}/superadmin/users`,
                title: 'Users',
                translateKey: 'nav.ecmc.superadmin.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
            {
                key: 'ecmc.superadmin.schools',
                path: `${ECMC_PREFIX_PATH}/superadmin/schools`,
                title: 'Schools',
                translateKey: 'nav.ecmc.superadmin.schools',
                icon: 'building',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPERADMIN],
                subMenu: [],
            },
        ],
    },

    // ─── TEACHER ──────────────────────────────────────────────────
    {
        key: 'ecmc.teacher',
        path: '',
        title: 'Teacher Portal',
        translateKey: 'nav.ecmc.teacher',
        icon: 'bookOpen',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [TEACHER],
        subMenu: [
            {
                key: 'ecmc.teacher.dashboard',
                path: `${ECMC_PREFIX_PATH}/teacher/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.teacher.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
            {
                key: 'ecmc.teacher.classes',
                path: `${ECMC_PREFIX_PATH}/teacher/classes`,
                title: 'My Classes',
                translateKey: 'nav.ecmc.teacher.classes',
                icon: 'folder',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
            {
                key: 'ecmc.teacher.assignments',
                path: `${ECMC_PREFIX_PATH}/teacher/assignments`,
                title: 'Assignments',
                translateKey: 'nav.ecmc.teacher.assignments',
                icon: 'clipboardCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TEACHER],
                subMenu: [],
            },
        ],
    },

    // ─── PARENT ───────────────────────────────────────────────────
    {
        key: 'ecmc.parent',
        path: '',
        title: 'Parent Portal',
        translateKey: 'nav.ecmc.parent',
        icon: 'users',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [PARENT],
        subMenu: [
            {
                key: 'ecmc.parent.dashboard',
                path: `${ECMC_PREFIX_PATH}/parent/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.parent.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
            {
                key: 'ecmc.parent.children',
                path: `${ECMC_PREFIX_PATH}/parent/children`,
                title: 'My Children',
                translateKey: 'nav.ecmc.parent.children',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PARENT],
                subMenu: [],
            },
        ],
    },

    // ─── STUDENT ──────────────────────────────────────────────────
    {
        key: 'ecmc.student',
        path: '',
        title: 'Student Portal',
        translateKey: 'nav.ecmc.student',
        icon: 'graduationCap',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [STUDENT],
        subMenu: [
            {
                key: 'ecmc.student.dashboard',
                path: `${ECMC_PREFIX_PATH}/student/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.ecmc.student.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.mypracticesets',
                path: `${ECMC_PREFIX_PATH}/student/my-practice-sets`,
                title: 'Practice Sets',
                translateKey: 'nav.ecmc.student.mypracticesets',
                icon: 'pencil',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.myquizzes',
                path: `${ECMC_PREFIX_PATH}/student/my-quizzes`,
                title: 'My Quizzes',
                translateKey: 'nav.ecmc.student.myquizzes',
                icon: 'clipboardCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.myattempts',
                path: `${ECMC_PREFIX_PATH}/student/my-attempts`,
                title: 'My Attempts',
                translateKey: 'nav.ecmc.student.myattempts',
                icon: 'chartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
            {
                key: 'ecmc.student.mysubscription',
                path: `${ECMC_PREFIX_PATH}/student/my-subscription`,
                title: 'My Subscription',
                translateKey: 'nav.ecmc.student.mysubscription',
                icon: 'creditCard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [STUDENT],
                subMenu: [],
            },
        ],
    },
]

export default ecmcNavigationConfig
